/// Definitive test: Use the cfb crate directly to build the OLE file.
/// This replaces our custom OLE writer (ole.rs) with the proven cfb crate.
/// The MSI data (tables, string pool, summary) is generated by our code.
///
/// If this works → custom OLE writer has a bug
/// If this fails → MSI data has a bug
use std::io::Cursor;
use std::process::Command;

fn main() {
    println!("=== Test: cfb crate + our MSI data ===\n");

    // Build MSI data using our code
    let mut b = velocity_msi::MsiBuilder::new();
    b.set_title("CFB Direct Test");
    b.set_author("Velocity");
    b.set_template("Intel", 1033);

    b.create_table("Property", vec![
        velocity_msi::Column::build("Property").string(72).primary_key().build(),
        velocity_msi::Column::build("Value").string(255).nullable().build(),
    ]).unwrap();
    b.insert_rows("Property", vec![
        vec![velocity_msi::Value::from("ProductName"), velocity_msi::Value::from("CFB Test")],
        vec![velocity_msi::Value::from("ProductVersion"), velocity_msi::Value::from("1.0.0")],
        vec![velocity_msi::Value::from("Manufacturer"), velocity_msi::Value::from("Velocity Corp")],
        vec![velocity_msi::Value::from("ProductCode"), velocity_msi::Value::from("{AADDD4E4-3A12-4B7D-A4E0-5A2F8B3C6D90}")],
        vec![velocity_msi::Value::from("UpgradeCode"), velocity_msi::Value::from("{BBDDE5F5-4B23-5C8E-B5F1-6B3A9C4D7EA1}")],
        vec![velocity_msi::Value::from("ProductLanguage"), velocity_msi::Value::from("1033")],
    ]).unwrap();

    b.create_table("Directory", vec![
        velocity_msi::Column::build("Directory").string(72).primary_key().build(),
        velocity_msi::Column::build("Directory_Parent").string(72).nullable().build(),
        velocity_msi::Column::build("DefaultDir").string(255).primary_key().build(),
    ]).unwrap();
    b.insert_rows("Directory", vec![
        vec![velocity_msi::Value::from("TARGETDIR"), velocity_msi::Value::Null, velocity_msi::Value::from("SourceDir")],
        vec![velocity_msi::Value::from("INSTALLDIR"), velocity_msi::Value::from("TARGETDIR"), velocity_msi::Value::from("VelTest:VelTest")],
    ]).unwrap();

    b.create_table("InstallExecuteSequence", vec![
        velocity_msi::Column::build("Action").string(72).primary_key().build(),
        velocity_msi::Column::build("Condition").string(255).nullable().build(),
        velocity_msi::Column::build("Sequence").int16().nullable().build(),
    ]).unwrap();
    b.insert_rows("InstallExecuteSequence", vec![
        vec![velocity_msi::Value::from("CostInitialize"), velocity_msi::Value::Null, velocity_msi::Value::Int(800)],
        vec![velocity_msi::Value::from("CostFinalize"), velocity_msi::Value::Null, velocity_msi::Value::Int(1000)],
    ]).unwrap();

    // Build using our normal path (custom OLE writer)
    let our_data = b.build().unwrap();
    println!("Our MSI: {} bytes", our_data.len());

    // Write our MSI, then open with cfb to extract streams
    let temp_path = "cfb_test_temp.msi";
    std::fs::write(temp_path, &our_data).unwrap();

    // Open with cfb crate
    let file = std::fs::File::open(temp_path).unwrap();
    let comp = cfb::CompoundFile::open(file).unwrap();

    // List all streams
    let entries: Vec<(String, bool)> = comp.walk()
        .map(|e| (e.path().to_string_lossy().to_string(), e.is_stream()))
        .collect();

    println!("\nStreams in our MSI:");
    for (path, is_stream) in &entries {
        if *is_stream {
            println!("  {}", path);
        }
    }

    // Now create a new OLE file using the cfb crate
    println!("\n--- Rebuilding with cfb crate ---");
    let out_cursor = Cursor::new(Vec::new());
    let mut new_comp = cfb::CompoundFile::create(out_cursor).unwrap();

    // Set MSI CLSID on root
    let msid_clsid = uuid::Uuid::parse_str("000c1084-0000-0000-c000-000000000046").unwrap();
    new_comp.set_storage_clsid("/", msid_clsid).unwrap();

    // Copy all streams from our MSI to the new cfb file
    let file2 = std::fs::File::open(temp_path).unwrap();
    let comp2 = cfb::CompoundFile::open(file2).unwrap();

    let stream_entries: Vec<String> = comp2.walk()
        .filter(|e| e.is_stream())
        .map(|e| e.path().to_string_lossy().to_string())
        .collect();

    drop(comp2);

    // Re-open and copy streams one by one
    let file3 = std::fs::File::open(temp_path).unwrap();
    let mut comp3 = cfb::CompoundFile::open(file3).unwrap();

    for stream_path in &stream_entries {
        // Read stream data from our MSI
        let data = {
            let mut reader = comp3.open_stream(stream_path.as_str()).unwrap();
            let mut buf = Vec::new();
            std::io::Read::read_to_end(&mut reader, &mut buf).unwrap();
            buf
        };
        println!("  Copying: {} ({} bytes)", stream_path, data.len());

        // Write to new cfb file
        let mut writer = new_comp.create_stream(stream_path.as_str()).unwrap();
        std::io::Write::write_all(&mut writer, &data).unwrap();
    }

    new_comp.flush().unwrap();
    let new_data = new_comp.into_inner().into_inner();
    println!("\nNew MSI (cfb): {} bytes", new_data.len());

    // Write and test
    let new_path = "cfb_direct.msi";
    std::fs::write(new_path, &new_data).unwrap();

    // Test both
    println!("\n=== Testing with msiexec ===");
    println!("\n--- Original (custom OLE writer) ---");
    let code_our = test_msiexec(temp_path);
    println!("Exit code: {}", code_our);

    println!("\n--- Rebuilt (cfb crate) ---");
    let code_cfb = test_msiexec(new_path);
    println!("Exit code: {}", code_cfb);

    // Summary
    println!("\n\n=== RESULTS ===");
    println!("Original (custom OLE): exit code {}", code_our);
    println!("Rebuilt (cfb crate):   exit code {}", code_cfb);

    if code_our != 0 && code_cfb == 0 {
        println!("\n>>> OLE WRITER BUG CONFIRMED!");
    } else if code_our != 0 && code_cfb != 0 {
        println!("\n>>> DATA BUG CONFIRMED! Both OLE layers fail.");
    } else if code_our == 0 {
        println!("\n>>> Original works!");
    }
}

fn test_msiexec(path: &str) -> i32 {
    let output = Command::new("msiexec")
        .args(&["/i", path, "/qn", "/norestart"])
        .output()
        .expect("msiexec failed");
    let code = output.status.code().unwrap_or(-1);
    if code == 0 {
        let _ = Command::new("msiexec")
            .args(&["/x", path, "/qn", "/norestart"])
            .output();
    }
    code
}
